### ISSUE TITLE
The `fuego.WithPort` option exposes the server to localhost only.

### ISSUE THREAD

**Issue by minpeter** [go-fuego/fuego#101]
```go
func WithPort(port int) func(*Server) {
	return func(s *Server) { s.Server.Addr = fmt.Sprintf("localhost:%d", port) }
}
```

In production, this code will cause the server to refuse the connection and eventually result in a Bad gateway.
It seems necessary to properly divide the production and development environments.

**Comment by minpeter** [comment]
```go
fuego.WithAddr("0.0.0.0:"+port),
```
There is a simple temporary workaround with the code above.

It would be a good idea to add or perform additional actions to the document. Please tell us what you want to do and we will create a PR accordingly.

**Comment by EwenQuim** [comment]
I just wanted to make the output pretty print the link http://localhost:<port> so it's clickable, but now you say that, it doesn't really makes sense.

I wasn't worried about localhost because our services run in localhost and are proxied to internet via a reverse proxy

**Comment by minpeter** [comment]
I am also using a reverse proxy, but since it runs in a different container from the service, it does not work if set to localhost.

This may be a somewhat personal argument, but if you want to set the default value in withPort to `fmt.Sprintf("0.0.0.0:%d", port)` and only expose it to localhost, how about configuring it through the `WithAddr` option?

It's simply a reversal of the traditional approach, but for beginners using this framework, there's less to think about and it's still clickable.
Also for go gin the default is 0.0.0.0 exposure.

**Comment by dylanhitt** [comment]
Defaulting to `0.0.0.0` is bad practice when it's not necessary. Some networks require that though, even in the container world you can bind a scoped listening address with on a per process basis. That being said. We really should keep the default Host value has `localhost`. I personally think exposing a `WithHost` option is the best call here. At that point we have pretty much every possible input covered. 

I think the bigger step here is documenting the defaults well.

Thoughts?

**Comment by minpeter** [comment]
The security office agrees. Let's supplement the document.
