### ISSUE TITLE
Ability to disable default tag on routes

### ISSUE THREAD

**Issue by dylanhitt** [go-fuego/fuego#105]
**Is your feature request related to a problem? Please describe.**
Currently we append tags to every route using the ResponseBody. In some cases users do not want this. For instance I would like only the `v2` tag for all routes in a server group. As I want my outputted node client to have all of it's function in the `v2api.js` file. This is still the result however a consequence of this is that we end up with another file exporting the same function name, ultimate failing the typescript buld. This leads to needed to do something along the lines of

```golang
rootProtected := fuego.Group(root, "/v2")

fuego.Get(rootProtected, "/accounts", h.Accounts).Tags("v2")

fuego.Get(rootProtected, "/clusters", h.Clusters).Tags("v2")
```

This essentially makes using tags at the group level not very useful. 

**Describe the solution you'd like**
Use the [OpenAPIConfig](https://github.com/go-fuego/fuego/blob/main/options.go#L19) struct to configure this behavior. I.e add a field of `NoDefaultTags` or whatever (open to name suggestions) 

**Describe alternatives you've considered**
The alternative is above.

**Comment by EwenQuim** [comment]
I think we might disable this feature in favor of https://github.com/go-fuego/fuego/issues/97#issuecomment-2016104273

**Comment by dylanhitt** [comment]
Ah, I'm in favor of the Group based default tag. However I think we should still provide a way to default this behavior in general.
