### ISSUE TITLE
HTTP2 or H2C support

### ISSUE THREAD

**Issue by redecs** [go-fuego/fuego#111]
How can I configure to use HTTP2? How about H2C?
The documentation doesn't mentioned anything about it and looking through the code I didn't manage to find anything that would shed some light on this.

As a long time user of API Platform (PHP), Fuego brings some familiar features to the Go ecosystem, so thank you! 🙇

**Comment by dylanhitt** [comment]
For the HTTP2 case. Are you asking how to only start the server where it will only listen for HTTP2 connections? I'm pretty sure the current state of the go stdlib is that it net/http server supports both and it's on the client to make the connection?

Are you asking can we force all connections to be http2 if not terminate?

**Comment by EwenQuim** [comment]
HTTP2 is indeed supported through `net/http`.

You have nothing to do or configure, just try, you'll see that the response mentions HTTP2.

![IMG_20240404_233759_778.jpg](https://github.com/go-fuego/fuego/assets/46993939/91a5dba8-feb1-4ea8-922c-0f2d5277aa3b)

---

If you want to accept only http2 connection, I suggest to search how to do it on standard Go, as Fuego relies on the std lib!

**Comment by dylanhitt** [comment]
Oh I see now. Thank you for the clarification. 

We should definitely provide an option to configure TLS. Maybe something like WithTLS(cert, key).

H2C will probably stay how you configured it. Also in that example I don't see why you can't just call server.Run().

**Comment by dylanhitt** [comment]
Or another implementation would be app.RunTLS(cert, key)

**Comment by redecs** [comment]
H2C it's not that common and I get why you wouldn't want to add that your API, it's fine. 

As per my H2C example, I can't call `server.Run()` because it [overrides](https://github.com/go-fuego/fuego/blob/v0.13.4/serve.go#L25) `Server.Handler` so I loose the bit that makes it all work: `h2c.NewHandler(s.Mux, h2s)`

As for the TLS bit, `RunTLS` feels more inline with how the `net/http` Server works and dare I say is more idiomatic, but it's not my call to make, I'm new here. But I'm will willing to put in a PR for either of those once a consensus is reached.

**Comment by dylanhitt** [comment]
I'm in the camp of RunTLS as well.

**Comment by dylanhitt** [comment]
As for the h2c overrides problem.

I believe the function  [WithCorsMiddleware](https://github.com/go-fuego/fuego/blob/v0.13.4/options.go#L161) will get you over the finish line. Unless I'm misreading something.

**Comment by redecs** [comment]
@dylanhitt you are right, this works just fine for h2c and I can just do `s.Run()`.

```go
s := fuego.NewServer(
    fuego.WithAddr("localhost:8088"),
    fuego.WithCorsMiddleware(func(h http.Handler) http.Handler { return cors.Default().Handler(h2c.NewHandler(h, &http2.Server{})) }),
)
```

**Comment by EwenQuim** [comment]
That's nice! 

It means our abstractions are good. But thank you for challenging the framework, that's how we make it robust!

**Comment by EwenQuim** [comment]
We should still implement the `RunTLS` feature, in a dedicated issue

**Comment by redecs** [comment]
Some additional thoughts on h2c:
The CORS middleware doesn't support h2c either, so in my example above CORS adds the allow headers only if I call it using HTTP/1.1. If like me, you are using H2C only for internal communication (server to server), then you don't even need CORS, so the configuration option would become:
```go
fuego.WithCorsMiddleware(func(h http.Handler) http.Handler { return h2c.NewHandler(h, &http2.Server{}) }),
)
```
A bit counter intuitive, but since it's such a niche use-case, I don't mind that is a bit counter intuitive. The functionality is there, the API is sound. If anyone else has since a fringe use-case like mine, they will hopefully find this issue and get their answer.

I think the starting question was answered, you can do both HTTP2 and h2c with Fuego. 
After adding `RunTLS` in, getting HTTP2 to work will be even easier.
Thank you both for you help and work on this! 🙇
