### ISSUE TITLE
Make it easier for Fuego to use TLS 

### ISSUE THREAD

**Issue by redecs** [go-fuego/fuego#113]
Starting from my inquiry about [HTTP2 support](https://github.com/go-fuego/fuego/issues/111), it is pretty clear that TLS configuration for Fuego could be easier. 

It looks like the consensus is to add a new method, `RunTLS(cert, key)` that will do the same thing as Run does but call `ListenAndServeTLS` at the end, with the supplied certificate and key.

I also think nobody wants to deal with certificate management manually since LetsEncrypt and the ACME protocol made that a thing of the past. So while suppling paths to certificate files would work fine, I would also like to explore the options to make TLS usage less of a pain. I also realize that using an ACME client library to make it easy to get certificates might fall out of the scope of the initial work we want to do, I think it's good to consider a path forward here before making changes.

My first thought is around how an implementation using something like [autocert](https://pkg.go.dev/golang.org/x/crypto/acme/autocert) would be like. Where are the integration points with Fuego?

What do you think?

**Comment by dylanhitt** [comment]
I'm pretty against having fuego do any automated certificate stuff. That's on the caller in my opinion. 

But that's just my opinion.

**Comment by redecs** [comment]
@dylanhitt I agree, also don't think Fuego should manage certificates automatically. What I meant is that we should look at how some of the libraries that do that work to make sure the API makes the integration easier.

Here an example: let's say I want to use TLS with certs from LetsEncrypt, I will setup `autocert` in my main.go and then I'll just hook it into Feugo somehow. Managing the certs (storage, renewal, etc) would my programs responsibility, not the framework's. I will try to come with some code to make it clear.

**Comment by dylanhitt** [comment]
Ah I see, yes, some thought into how we expose the server TLS config could be fruitful. It is annoying when you need to do anything a bit more low level.

**Comment by dylanhitt** [comment]
Hey @redecs curious if you were gonna work on this?

Thanks

**Comment by redecs** [comment]
@dylanhitt Yes, I am. Will try to open a PR later today to get some feedback.

**Comment by dylanhitt** [comment]
closed by #120
