### ISSUE TITLE
openapi spec for non 200 responses

### ISSUE THREAD

**Issue by jhsc** [go-fuego/fuego#127]
**To Reproduce**
Not sure if this is a bug, or just not implemented yet but I noticed that when the openapi spec is generated there is no error responses. It just generated 200's responses, but in the case we want to have non 200 responses included in the openapi spec how would this be possible? Is there documentation how to generate error responses for handlers?

**Expected behavior**
For example I have this 

```
"/login": {
      "post": {
        "description": "Authenticates User",
        "operationId": "POST /login:Handler",
        "requestBody": {
          "$ref": "#/components/requestBodies/LoginReq"
        },
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResp"
                }
              }
            },
            "description": "OK"
          },
          "default": {
            "description": ""
          }
        },
        "summary": "Login",
        "tags": [
          "Login"
        ]
      }
    }
```

I would want to add to the responses spec
```
"responses": {
          "200": {
            ......
            },
           "401": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/BadResp"
                }
              }
            },
          },
```

**Framework version (please check if it happens with the last Fuego version before posting):**
github.com/go-fuego/fuego v0.13.1

**Go version (please check if it happens with the last Go version before posting):**
1.22.1

**Comment by EwenQuim** [comment]
We'll work on this after #64 ! In the meantime you can still build a response by using the `operation` given by `fuego.Get`
