### ISSUE TITLE
Default http.server configuration prevents Docker deployment

### ISSUE THREAD

**Issue by oerni74** [go-fuego/fuego#129]
Hi,

first of all I would like to say that I really like working with Fuego. It is a nice experience so far.

However, I recently wanted to deploy my Fuego application to the Cloud (Google Cloud Run) and there are some problems with the default behavior imho. 
The `fuego.NewServer()` function automatically calls the `withPort()` function, which itself sets the `Addr` field of the underlying http/server to *localhost:port*. Unfortunately, this has a side effect. When running the application inside a Docker container, you have to add the `--net=host` argument to make it accessible from the outside. This is different from the default bahavior of the `http/server`  where the `Addr` field is just set to *:port*.

I would have expected that `withPort` only sets the port and not the host. In the end the only solution for Cloud Run was to use `withAddr(":"+port)`. Then it can be accessed via the browser on *localhost:8080*, however the log says *Server running ✅ on http://:8080*, which is a bit confusing.
Therefore, I would suggest to make the behavior equal to the one in the standard library to avoid confusion when making a deployment.

That being said, I am still new to Go, so maybe there is a deeper reason I don´t know yet :smile:)

**To Reproduce**

1. Create a new fuego server
`fuego.NewServer()`
3. Dockerize the application (example Dockerfile: https://github.com/GoogleCloudPlatform/cloud-run-hello/blob/master/Dockerfile)
4. Run the Docker container with the default bridge network
5. (optional) Run the Docker container in the cloud (e.g. on Google Cloud Run)
6. Try to access the application.

**Expected behavior**
Application is accessible without further configuration like when using the standard library `http/server`.

**Framework version (please check if it happens with the last Fuego version before posting):**
0.13
**Go version (please check if it happens with the last Go version before posting):**
1.22

**Comment by chenjr0719** [comment]
I think using `fuego.WithAddr("0.0.0.0:8080")` when creating a new server should work.
https://go-fuego.github.io/fuego/docs/guides/options#address

Could you give it a try?

**Comment by EwenQuim** [comment]
I will fix the behaviour of WithAddr in next version.

Don't forget that in the meantime you can always access `server.Addr` as it is a public field and not used before `server.Run()`

**Comment by dylanhitt** [comment]
@EwenQuim not sure I understand? What seems to be the problem with WithAddr?

**Comment by dylanhitt** [comment]
@oerni74 was you issue resolved? If so please close.
