### ISSUE TITLE
New releases or a public roadmap.

### ISSUE THREAD

**Issue by carlosbensant** [go-fuego/fuego#131]
Do you have an ETA for the next version? It's been months without any new releases.

First of all, this project looks great so far. I'm still in the phase of playing with Fuego but before deciding to use it on a real project, I would like to know if it will be actively maintained and which features we can expect to be included shortly.

I would like to help with the website, documentation, and/or populating the repo with example projects targeting new Go developers.

**Comment by EwenQuim** [comment]
Yes the project is still under development!

I hadn't have the time last months to code on this project but we have huge features planned and some of them are already in draft.

Also, don't forget that this is an open-source project, so don't be afraid to send your own inputs :)

Happy coding 🔥
