### ISSUE TITLE
Serialised errors are missing details

### ISSUE THREAD

**Issue by gxvxc** [go-fuego/fuego#146]
**To Reproduce**

1. Return an error with `Info()` from controller
4. Serialised `Detail` is missing from the response

**Expected behavior**
Should add `Detail` to serilised response

**Framework version:** 0.13.4

**Go version:** 1.22

**Additional context**
[The documentation website](https://go-fuego.github.io/fuego/docs/guides/errors/#error-handling-in-fuego) mentions an `Info()` method with incomplete type signature. [errors.go](errors.go#L111) mentions an `ErrorWithInfo` interface, but such interface seems not be part of the codebase. I haven't looked through the repo history for it in case it's deleted unintentionally, but I'd be happy to work on a PR to add it.

**Comment by EwenQuim** [comment]
Hi ! Can you add a code to test and the expected behaviour please?

**Comment by EwenQuim** [comment]
#150 and a new release will fix this issue :)

**Comment by EwenQuim** [comment]
v0.14 fixes this issue and is already available :)
