### ISSUE TITLE
Function 'Register' overwrites the provided Route.Operation

### ISSUE THREAD

**Issue by NorbertHauriel** [go-fuego/fuego#156]
**Is your feature request related to a problem? Please describe.**
I expected Route.Operation to be applied by 'Register', given its exported visibility scope. Had to look into the implementation to see it is completely ignored.

**Describe the solution you'd like**
Use the already existing 'Route.Operation' (when not nil).  This way the default field assignments for 'Route.Operation' (such as 'Summary', 'Description', 'OperationID', or any others to be added in the future) are not forcefully overwritten when the user clearly has its own Operation object already made.

**Describe alternatives you've considered**
An alternative solution could be to make the 'Route.Operation' field private, if that was the original intention.

**Additional context**
The use case of the preferred solution is that sometimes you know some or all the Operation fields beforehand, and other times you have a dynamic logic that passes the Route struct and conditionally calls the different field setters on it for example:
Route.Summary("mySummary")
Route.Description("myDesc")
Route.OperationID("myID")

I think this proposal would add a new feature without much effort to implement. Let me know if you would like me to do it, and whether my proposal is feasible in your current design/vision.

Thank you for this package @EwenQuim !

**Comment by EwenQuim** [comment]
Indeed, very good point. I think we should make `Operation` able to set through the `Register` function. I made it public so users can access and modify it after route registration.

For now I'm just adding a comment, but I'll work on making it settable through `Register`
