### ISSUE TITLE
Spec should not assume xml responses

### ISSUE THREAD

**Issue by dylanhitt** [go-fuego/fuego#159]
Fuego is generating xml schema for all routes do to: https://github.com/go-fuego/fuego/blob/main/openapi.go#L171.

Assuming XML for every route is not great as to support XML routes in go requires a fair amount of work on `xml:` tags on a struct to ensure XML encoding doesn't error.

We should only ever assume json when not specified, and allow for user input when a user wants the route to accept something different.

**Screenshots**

**Framework version (please check if it happens with the last
v0.14.0

**Go version (please check if it happens with the last Go version before posting):**
v1.22.6

I figure something like

`Route.RequestContent(...string)` and `Route.ResponseContent(...string)`

and we default to json when nothing is provided.

Maybe later we add the ability to default the whole server to XML but want to keep the initial case scoped. How does that sound? I'm open to better naming as well.

**Comment by dylanhitt** [comment]
@EwenQuim you have any opinions on this? If not I'll be implementing it sometime this week.

**Comment by EwenQuim** [comment]
As of v10.14, Fuego controllers can decode JSON or XML bodies, based on the `Content-Type` header.
But indeed, the generated OpenAPI documentation does not match the xml tags. We can use something like `Route.RequestContent(...string)` as you proposed.

For the output, I'd like to keep the fact that the user can ask for a return type or another without the need for the developer to provide anything. But we can discuss this. The generated OpenAPI spec should be in sync too...

**Comment by dylanhitt** [comment]
That is fair.

To describe a little bit how intentional a user must be to support `xml` in responses. Per the Marshal documentation from `encoding/xml` - https://pkg.go.dev/encoding/xml#Marshal

> Marshal will return an error if asked to marshal a channel, function, or map.

In the case where any return type is a map the user needs to implement their own `MarshalXML` function.
