### ISSUE TITLE
Controller package generation through the CLI creates a file in a package `controller` instead of `controllers`, in the `controllers` folder

### ISSUE THREAD

**Issue by biancarosa** [go-fuego/fuego#163]
**To Reproduce**

1. Run `go run github.com/go-fuego/fuego/cmd/fuego@latest controller books`
2. Try to follow documentation steps.
3. Get an error because package controllers does not exist.

**Expected behavior**
- Package controllers should exist.
- We should be able to call `controllers.BooksRessources{}.Routes(s)` without having to change the package name inside of the generated file.

**Screenshots**
N/A

**Framework version (please check if it happens with the last
Fuego version before posting):** `v0.14.0`

**Go version (please check if it happens with the last Go version before posting):**  `go1.22.6 darwin/amd64`

**Additional context**
The docs are partially correct because of this; we need to make a decision whether to keep controllers vs controller and ensure the docs follow this naming convention. If we decide to keep `controller` as the package name, I'd suggest renaming the folder and we still need to update the example in the docs accordingly.

**Comment by EwenQuim** [comment]
Yes, I agree that the package name should match exactly the folder.

There are other "s" typos to fix in this CLI, I will work on this tomorrow.

Thanks for reporting and sorry for the long delay!

**Comment by EwenQuim** [comment]
Also, don't hesitate to make a PR for this kind of issue. It might be frightening to contribute to open-source but it really isn't!

This kind of issue is perfect for newcomers to try the "open-source workflow".
I will tackle this tomorrow if you don't have time today.

Happy coding :)

**Comment by biancarosa** [comment]
I can tackle this for sure! Somewhere in between tomorrow and Sunday.

**Comment by EwenQuim** [comment]
Hi @biancarosa !

Did you have time to work on this?

Don't hesitate to open a draft PR even
