### ISSUE TITLE
Can't get all values from query params

### ISSUE THREAD

**Issue by dhanielsales** [go-fuego/fuego#167]
First of all, I simply loved the idea of ​​the project! Congrats! 

Usually I create a similar structure for my personal projects and it was really fun seen it here, so I'll try to contib with my experiences :)

So, going to the suggestion: 
I noticed that the interfaces `fuego.ContextWithBody[Body]` and of couse, `fuego.ContextNoBody` doesn't have a method to grab all Query params from the request, insted of it, you only have those methods to handle with query params:

```go
QueryParam(name string) string
QueryParamInt(name string, defaultValue int) int // If the query parameter does not exist or is not an int, it returns the default given value. Use [Ctx.QueryParamIntErr] if you want to know if the query parameter is erroneous.
QueryParamIntErr(name string) (int, error)
QueryParamBool(name string, defaultValue bool) bool // If the query parameter does not exist or is not a bool, it returns the default given value. Use [Ctx.QueryParamBoolErr] if you want to know if the query parameter is erroneous.
QueryParamBoolErr(name string) (bool, error)
QueryParams() map[string]string
```

Non of them can handle with multiple values, so my suggestions is to add a new method like `QueryParamArr(name string) []string` to handle with this type of things.

Also, for the `QueryParams() map[string]string` I would not recoment you guys to treat the query params as an `map[string]string` because it will suffer by the same problem which I mentioned just above. So, my seconde suggestion is to change it for `url.Values`. It is an standard type for query params in go and it's a `map[string][]string`.

So, as I said in another issue, I already know how to fix thos problems, if you want I can open a PR with the fix :)

Take care :D

**Comment by EwenQuim** [comment]
Yes very good idea!

Happy to review a PR if you have time. I'll do it next monday otherwise, I'm pretty busy this weekend.

Thank you for reporting this, feedback is always valuable 🙏🏼

**Comment by drwpls** [comment]
@EwenQuim It's should be `fuego.ContextWithParams[T]` there to automatic format incoming GET request parameters, which should be use like:
```Go
fuego.Get(api, "/test", func(c fuego.ContextWithParams[types.TestRequest] (*types.TestResponse, error) {
		req := c.Params()
		// handle this req params
                _ = req
		return &types.TestResponse{
			hello: "world",
		}, nil
	})
```

The parameters parsing can be use inside fuego (from `*http.Request`:
```Go
func ParseFormValues[T any](r *http.Request) (*T, error) {
	if err := r.ParseForm(); err != nil {
		return nil, fmt.Errorf("parseform: %w", err)
	}

	params := make(map[string]any, len(r.Form))
	for key, value := range r.Form {
		switch len(value) {
		case 0:
			continue
		case 1:
			params[key] = value[0]
		default:
			v := make([]string, len(value))
			copy(v, value)
			params[key] = v
		}
	}

	res := new(T)
	decoder, err := mapstructure.NewDecoder(&mapstructure.DecoderConfig{
		DecodeHook: DecodeHook,
		Result:     res,
	})

	if err != nil {
		log.Fatal("failed to get a new decoder: ", err)
	}
	if err := decoder.Decode(params); err != nil {
		return nil, err
	}

	return res, nil
}
````

The `DecodeHook` is a function to parse Go type like `time.Time`, e.g. my types.Request should like: 
```Go
type CentralServerTopoServerServerRequest struct {
	CreatedAt netip.Addr `json:"from" validate:"required"`
}
```

**Comment by drwpls** [comment]
@EwenQuim  It's should be `fuego.ContextWithParams[T]` there to automatic format incoming GET request parameters, which should be use like:
```Go
fuego.Get(api, "/test", func(c fuego.ContextWithParams[types.TestRequest] (*types.TestResponse, error) {
		req := c.Params()
		// handle this req params
                _ = req
		return &types.TestResponse{
			hello: "world",
		}, nil
	})
```

The parameters parsing can be use inside fuego (from `*http.Request`:
```Go
func ParseFormValues[T any](r *http.Request) (*T, error) {
	if err := r.ParseForm(); err != nil {
		return nil, fmt.Errorf("parseform: %w", err)
	}

	params := make(map[string]any, len(r.Form))
	for key, value := range r.Form {
		switch len(value) {
		case 0:
			continue
		case 1:
			params[key] = value[0]
		default:
			v := make([]string, len(value))
			copy(v, value)
			params[key] = v
		}
	}

	res := new(T)
	decoder, err := mapstructure.NewDecoder(&mapstructure.DecoderConfig{
		DecodeHook: DecodeHook,
		Result:     res,
	})

	if err != nil {
		log.Fatal("failed to get a new decoder: ", err)
	}
	if err := decoder.Decode(params); err != nil {
		return nil, err
	}

	return res, nil
}
````

The `DecodeHook` is a function to parse Go type like `time.Time`, e.g. my types.TestRequest should like: 
```Go
type TestRequest struct {
	CreatedAt netip.Addr `json:"from" validate:"required"`
}
```

The validation process can be accomplished the same way like using `InTransform` like `ContextWithBody`

**Comment by EwenQuim** [comment]
We're more likely to support #174 instead of the proposed syntax, for the reasons enumerated above
