### ISSUE TITLE
ErrorHandler does not print status correctly

### ISSUE THREAD

**Issue by MaikelH** [go-fuego/fuego#180]
**Actual behavior**
When the `ErrorHandler` logs the error message, the status field is incorrectly outputted as `!ERROR:json: unsupported type: func() int`. See the full log message below:
```
{
    "time": "2024-08-29T13:08:15.93402122Z",
    "level": "ERROR",
    "msg": "Error Internal Server Error",
    "status": "!ERROR:json: unsupported type: func() int",
    "detail": "",
    "error": ""
}
```

**Expected behavior**
See below output
```
{
    "time": "2024-08-29T13:08:15.93402122Z",
    "level": "ERROR",
    "msg": "Error Internal Server Error",
    "status": 500,
    "detail": "",
    "error": ""
}
```

**Go version (please check if it happens with the last Go version before posting):**
`1.23`

**Comment by EwenQuim** [comment]
Can you give us your code and the corresponding HTTP request please ?

**Comment by MaikelH** [comment]
Sure, I can create a simple example. The problem is pretty simple to fix. The problem is that the `StatusCode` function is not called but passed as a function pointer.  See also attached PR #181
