### ISSUE TITLE
The full-app-gourmet example appears to be broken

### ISSUE THREAD

**Issue by asahasrabuddhe** [go-fuego/fuego#183]
**To Reproduce**

1. Go to `fuego/examples/full-app-gourmet/views/recipe.go`
2. Scroll down to line 100.
4. `templa.Home`, `templa.HomeProps` on line 100, `templa.SearchPage` and `templa.SearchProps` on 114 and similar functions below are not defined.

**Expected behavior**
The example in question should build without error.

**Screenshots**
![CleanShot 2024-09-01 at 12 44 38@2x](https://github.com/user-attachments/assets/98c0ac5b-e700-4235-89fa-d77e7848f7ac)

**Comment by EwenQuim** [comment]
You have to run `go generate ./...` to generate the templates. It's how the [templ](https://github.com/a-h/templ) lib works.

**Comment by asahasrabuddhe** [comment]
> You have to run `go generate ./...` to generate the templates. It's how the [templ](https://github.com/a-h/templ) lib works.

Thanks. It seems to be working as expected now. I was running `go generate` instead of `go generate ./...`. I will close this issue.
