### ISSUE TITLE
Add a CI for detecting typos

### ISSUE THREAD

**Issue by ccoVeille** [go-fuego/fuego#188]
Following #187, may I suggest to set up a CI for catching obvious typos?

I did it on many repository, I can help.

I would suggest a linter that has almost no false positive

**Comment by EwenQuim** [comment]
Ok, why not!

Can you add it in the Makefile too? Thanks!

**Comment by imransolanki** [comment]
Can you please review and approve the PR here - https://github.com/go-fuego/fuego/pull/189

**Comment by asahasrabuddhe** [comment]
This one has been addressed with #189. This one can be closed!

**Comment by ccoVeille** [comment]
Misspell is fine, I planned to add it too.

So thank you!

but unfortunately it is not enough for documenation in Markdown files.

Please let this issue open, I'll open a PR soon
