### ISSUE TITLE
Full gourment adming app form not working

### ISSUE THREAD

**Issue by thirdknife** [go-fuego/fuego#191]
**To Reproduce**

1. Go to `admin/recipes/create` after running the app
2. When you fill Name for a recipe and change to next form field
3. Page gets redirected to `admin/recipes/` without completing the form 

**Expected behavior**
Should let fill and submit the form.

Go version
1.22.6 linux/amd64

**Comment by EwenQuim** [comment]
Sorry I want to finish #176 before fixing this! But I'll look at it soon.

Don't hesitate to open a PR if you want to investigate :)

**Comment by dylanhitt** [comment]
Imma take this. I need to learn the examples a bit better
