### ISSUE TITLE
Try out gomponents at new module path

### ISSUE THREAD

**Issue by markuswustenberg** [go-fuego/fuego#198]
**Is your feature request related to a problem? Please describe.**

I'm trying to move gomponents to a new module path, `maragu.dev/gomponents`. If you have the time and would like to help out, could you do `go get maragu.dev/gomponents@v1.0.0-beta1`, global-replace the old import path with the new one in Go files, and see whether everything still works?

**Describe the solution you'd like**

I would like it to still work. :D

**Describe alternatives you've considered**

Not moving the import path.

**Additional context**

https://github.com/maragudk/gomponents/releases/tag/v1.0.0-beta1

**Comment by EwenQuim** [comment]
Works well

**Comment by markuswustenberg** [comment]
@EwenQuim thank you for the quick response! Excellent. I've also not hit any issues yet migrating a large codebase.
