### ISSUE TITLE
Data race due to global instance of openapi3gen.Generator

### ISSUE THREAD

**Issue by loikg** [go-fuego/fuego#201]
**To Reproduce**
Create multiple instance of `fuego.Server` in different goroutines.
I have create a simple repository to showcase the problem over [here](https://github.com/loikg/fuego-datarace-reproduce). But for sake of completeness here the test used:

```go
package main

import (
	"fmt"
	"testing"

	"github.com/go-fuego/fuego"
)

func TestDataRace(t *testing.T) {
	t.Parallel()

	for n := range 2 {
		t.Run(fmt.Sprintf("create server %d", n), func(t *testing.T) {
			t.Parallel()
			createFuegoServer(t)
		})
	}
}

func createFuegoServer(t *testing.T) {
	t.Helper()

	server := fuego.NewServer()
	fuego.Get(server, "/", func(ctx *fuego.ContextNoBody) (any, error) {
		return nil, nil
	})
}
```

**Expected behavior**
The data race should not happen.

**Framework version:**
Tested on v0.14.0 and main at the time of writing ([f386d4f](https://github.com/go-fuego/fuego/commit/f386d4f4842ec3b49eb99e26d5df0b04b8706bd6)).

**Go version:**
v1.23.2

**Additional context**
This prevent running tests that exercise the entire server in parallel, but does not affect unit test of handlers as far as I understand.
The root cause is the package global variable `generator` at line  [151](https://github.com/go-fuego/fuego/blob/f386d4f4842ec3b49eb99e26d5df0b04b8706bd6/openapi.go#L151) in openapi.go being shared and concurrently used by every `fuego.Server` instances.
See #202 for a potential fix.

Huge thanks for your work, I really enjoy using fuego!

**Comment by EwenQuim** [comment]
Wow I didn't thought that someone would use several instances of `fuego.Server` haha.

Just a side question : why do you need that?

Thanks for raising this issue :)

**Comment by loikg** [comment]
No worries. The reason is purely to be able to run tests in parallel.

I took the habit of making every test that I can run in parallel with `t.Parallel()` and in some of my tests I want to test the entire "stack" including middlewares that should be trigger when calling a specific endpoint, thus these tests create multiple `fuego.Server` instances in parallel leading to the data race.

**Comment by EwenQuim** [comment]
Very good idea indeed
