### ISSUE TITLE
Howto use openTelemetry (for Traces)

### ISSUE THREAD

**Issue by wrenix** [go-fuego/fuego#207]
To store and evaluate in Tempo and/or Jaeger.

https://opentelemetry.io/docs/languages/go/

**Comment by EwenQuim** [comment]
Since Fuego is fully compatible with `net/http`, I believe the oficial otel lib is already compatible https://pkg.go.dev/go.opentelemetry.io/otel.

But if you want to integrate this into the framework we might keep this issue.

**Comment by adreasnow** [comment]
@wrenix Just to further this, the [otelhttp](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp) middleware can be used with `fuego.Use()` as described in the docs [here](https://go-fuego.github.io/fuego/docs/guides/middlewares). [This](https://github.com/open-telemetry/opentelemetry-go-contrib/blob/1fdd2f63550ddd6338360d8e948e11b785a2956b/instrumentation/net/http/otelhttp/example/server/server.go#L82) is the handler func that you'd use 🙂

**Comment by adreasnow** [comment]
There's really no need to implement anything unless you want the OTEL initialisation process to be a `fuego.WithOTEL()` config option, but that would just be wrapping OTEL which needs to be configured specifically for each project anyway.

To use OTEL you just need to apply the middleware like this:

```go
	fuego.Use(s, otelhttp.NewMiddleware("",
		otelhttp.WithSpanNameFormatter(func(operation string, r *http.Request) string {
			return fmt.Sprintf("%s %s", r.Method, r.URL.Path)
		}),
		otelhttp.WithFilter(filters.Not(filters.Path("/ping"))),
	))
```

In this setup I use fuego in a k8s pod, so I don't want me telemetry to be spammed by the health check endpoint `/ping`

**Comment by EwenQuim** [comment]
Thank you very much for your contribution @adreasnow!

Closing because all the questions asked here are answered, but @wrenix don't hesitate to reopen if you feel you're not satisfied.

**Comment by pdrvsky** [comment]
Hey guys, I've stumbled upon the same need and created a simple solution. Feel free to check it: https://github.com/pdrvsky/otelfuego
