### ISSUE TITLE
Generate Metrics for Monitoring

### ISSUE THREAD

**Issue by wrenix** [go-fuego/fuego#208]
**Describe the solution you'd like**
Support both:
- Prometheus metric endpoint
- opentelemetry-metrics

**Additional context**
OpenTelemetry library support Prometheus-Exporter

**Comment by adreasnow** [comment]
@wrenix This should be handled by the solution in #207 I'd imagine.

What specifically would you like to be exported to prometheus beyond what is provided by OTEL already?
