### ISSUE TITLE
Middleware for Sessions and OIDC

### ISSUE THREAD

**Issue by wrenix** [go-fuego/fuego#209]

**Comment by EwenQuim** [comment]
There's already a `Security` struct in the `security.go` file but it deserves to be worked on. I think we should also move it to the `extras` folder.

**Comment by EwenQuim** [comment]
As you can always use [gorilla/sessions](https://github.com/gorilla/sessions), I'm closing. 

Fuego adds no value here. If you wish to integrate the security to your OpenAPI spec, there's now the possibility to define `securitySchemes` and their per-route usage thanks to #226

**Comment by EwenQuim** [comment]
Thank you for your suggestions and helping other that will find these links!
