### ISSUE TITLE
WithGlobalResponseTypes should also return XML

### ISSUE THREAD

**Issue by DimShadoWWW** [go-fuego/fuego#247]
I would like the response type to be configurable.

schema:
```
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Example"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Example"
                }
              }
            },
            "description": "OK"
          },
          "400": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPError"
                }
              }
            },
            "description": "Bad Request _(validation or deserialization error)_"
          },
          "500": {
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/HTTPError"
                }
              }
            },
            "description": "Internal Server Error _(panics)_"
          },
```

It inserts "application/json" and it is before "application/xml", this caused it to be selected as default Content-type on documentation.

Also, all errors use "application/json" because there is no way to specify other content-type for them.
(`fuego.WithGlobalResponseTypes` do not change it)

**Comment by dylanhitt** [comment]
`option.RequestContentType("application/xml; charset=UTF-8")` isn't for Bodies it's' for Requests. The code above is only showing requests. 

The response types are hardcoded currently

```
responseSchema := SchemaTagFromType(s, *new(T))
	content := openapi3.NewContentWithSchemaRef(&responseSchema.SchemaRef, []string{"application/json", "application/xml"})
	response := openapi3.NewResponse().WithDescription("OK").WithContent(content)
	route.Operation.AddResponse(200, response)
```

This issue wouldn't be a bug. More a feature request I believe.

**Comment by dylanhitt** [comment]
Ah here it is #159

**Comment by DimShadoWWW** [comment]
I am unable to change the tag to "Feature-request."

Currently, I am working on updating the OpenAPI structure, but I hope that "fuego" can eventually provide a way to specify it directly.

Thank you!

**Comment by dylanhitt** [comment]
Would you mind editing your issue to better reflecting the request. 

Basically stating you want response type to be configurable. At the very least we should update errors to also have an xml response. 

I assume the API you're working on here doesn't support json at all?

**Comment by DimShadoWWW** [comment]
Sure, I updated the the first comment.

I am working on an API that defaults to responding with XML. However, it will optionally support responding in JSON if explicitly requested via the `Accept` header.

But now it selects JSON by default when trying in the documentation, because "application/json" es the first option.

**Comment by EwenQuim** [comment]
@DimShadoWWW I think #251 answers your request!

Please have a look at the tests, or at #252, an example where the user can generate its own 200 OpenAPI response.

**Comment by dylanhitt** [comment]
#251 only satisfies the `200` response not the error response. `WithGlobalResponseTypes` should be updated to allow content types to be specified IMO

**Comment by dylanhitt** [comment]
After @EwenQuim's PR #255 I believe this is possible through accessing fields directly. However we should provide something. I believe all that needs to happen here is the option of [option.AddError](https://github.com/go-fuego/fuego/blob/main/option.go#L249) needs to allow for the input of content-types in it's signature. So

`func OptionAddError(code int, description string, contentTypes []string, errorType ...any) func(*BaseRoute)`

if nil or len of 0 we default to xml and json.

Anyone have any other ideas?

**Comment by dylanhitt** [comment]
We could also make `errorType` a structure of

```golang
type ErrorType struct{
  ContentTypes []string
  Type any
}
```

**Comment by EwenQuim** [comment]
Allowing a list of content type can be a good idea.

I think `AddError` should be renamed to accept any type. In reality, users might want to add a return type even for 200 request (if using std handler for example) or for 204 No Content. If you're ok we'll deprecate AddError

And yes it's better to have a list of struct {content type, custom type}.

**Comment by dylanhitt** [comment]
Sounds good. I’ll get something going over the weekend and yeah let’s deprecate AddError.
