### ISSUE TITLE
Neither the Generated nor Manual code from the `tutorial` →`CRUD` page seems to work

### ISSUE THREAD

**Issue by justinclift** [go-fuego/fuego#249]
**To Reproduce**

1. Go to https://go-fuego.github.io/fuego/docs/tutorials/crud
2. Try the "Generation" approach (literally cut-n-pasting the examples)

The Go code doesn't even compile:

```
$ go run .
# hello-fuego
./main.go:7:2: "hello-fuego/controllers" imported as controller and not used
./main.go:18:20: undefined: controllers
./main.go:19:17: undefined: controllers
```

This looks to be caused by the generation code mis-generating the books.go package declaration as `package controller`, when it should be `package controllers`.  It's missing the `s` on the end.

If the package name has really been changed in generated code, then the docs (especially the docs for new users) should be updated to match. :smile:

Also, the text fragment 'Ressources' is misspelled throughout the generated code which leads to other compilation problems.  Renaming it to be `Resources` throughout books.go fixes that problem and the generated code then runs.

---

So, lets try the Manual approach from that page too.  Replacing the existing `main.go` and `controllers/books.go` with the code from the page just throws a different error:

```
$ go run .
# hello-fuego
./main.go:28:32: in call to fuego.Delete, type func(c *fuego.ContextNoBody) error of controllers.DeleteBook does not match inferred type func(*fuego.ContextNoBody) (T, error) for func(Contexted) (T, error)
```

**Expected behavior**

Tutorial code is generally expected to work. :wink:

**Screenshots**

n/a

**Framework version (please check if it happens with the last
Fuego version before posting):**

Whatever `go install github.com/go-fuego/fuego/cmd/fuego@latest` installed, about an hour ago.

**Go version (please check if it happens with the last Go version before posting):**

```
$ go version                                           
go version go1.23.4 darwin/arm64
```

**Additional context**

**Comment by justinclift** [comment]
Looks like the `Ressources` typo was already fixed in https://github.com/go-fuego/fuego/pull/179.

Sounds like a new Fuego release (including that fix) needs to happen? :smile:

**Comment by EwenQuim** [comment]
Oh yes, releasing a new tag is enough, thanks for the report. It's done now!

Also, CRUD example fixed. Hard to check wheter examples from a .md file is compiling or not automatically. Do you have any idea, to avoid future defects?

**Comment by justinclift** [comment]
> Do you have any idea, to avoid future defects?

On a kind of funny / ironic note, isn't Swagger itself supposed to help keep docs updated with the code? :rofl:

That being said, I'm not aware of a good automated way to actually have some kind of link between any given examples and the code that compiles it.  In the other projects I've put time into, they commonly get a bit out of date vs the latest code as well (until people file bug reports!). :grin:

**Comment by justinclift** [comment]
Thanks for getting this issue fixed pretty much right away too.  That's a good sign for the project. :smile:

**Comment by EwenQuim** [comment]
Thank you! Closing, but don't hesitate to reopen if you think we must do something more long-term for the code in the `.md` files

**Comment by justinclift** [comment]
Just took a look at this again, and can confirm it's generating things correctly now.  Awesome. :smile:

As a thought for this CRUD example, I wonder if an initial book entry should be created so people can browse to the `/books` end point without the server panicing?

**Comment by EwenQuim** [comment]
Thanks!

I'm planning on adding a generator for services (basic in-memory) to be able to play with the example!

**Comment by justinclift** [comment]
Had a thought the other day about how to potentially automatically keep the docs up to date with the code.  Or at least have things automatically flag when it breaks.

If the examples on the website can have some html comment tags embedded just before and after them, then it should be possible to reliably have a GitHub Actions task pull them from the live website and compile them on every commit to the main development branch.

Something along the lines of:

```
<!-- Example 1 main.go START -->
package main

import (
	"github.com/go-fuego/fuego"

	"hello-fuego/controller"
)

[etc]
<!-- Example 1 main.go END -->
```

Then the GitHub Action could use some basic curl and shell scripting to pull down the example page(s) and extract the .go code for testing if compiling still works.

---

The other approach would be to have the examples in a git repo somewhere, and have the website build process grab them from that repo to embed in the website.  Then a GitHub Action (that runs on every commit to the main dev branch) could do a test compile of the code directly from that git repo rather than having to pull the code from the website.

Either way should work decently well.

**Comment by justinclift** [comment]
With the service generator thought, it's not a bad idea.  I noticed yesterday that the "Manual" example code (for the CRUD books example) doesn't panic when the `/books` end point is called due to it simply returning an empty `Book{}`.

Perhaps that's the only change needed for the generated CRUD example to work? ie make sure the memory structure it's trying to access has been allocated
