### ISSUE TITLE
Request & Response Logger

### ISSUE THREAD

**Issue by EwenQuim** [go-fuego/fuego#265]
**Is your feature request related to a problem? Please describe.**

A middleware, enabled by default but desactivable via a server option, that logs:
- when a request enters into the server, showing method, path, params (but not body) and the request id
- when a response goes out of the server, showing the response code and answer time, and the corresponding request id

You can create a new `default_middlewares.go` and the option to activate/desactivate it should be in the `server.go` file

**Comment by dylanhitt** [comment]
couple things to add and question. 

Please allow for disablement of one logger or other. In an environment that uses a saas product for their monitoring infra logging both the request and the response can cause a lot of costs! Also I assume the default should be with slog?

**Comment by dylanhitt** [comment]
One more though on request id here. What are the thoughts checking if the header of `X-Request-ID` is on the if there use it if not generate a random uuid?

**Comment by EwenQuim** [comment]
Yes, yes and yes! Good ideas :) 

Also, if the request can be DEBUG and the response INFO, it would be nice !

**Comment by dylanhitt** [comment]
Yeah I agree with you after playing around a bit tonight. The request log should just be debug. Trying to make everything configurable isn't worth the squeeze. It ends up just being easier to create your own logger middleware.

**Comment by dylanhitt** [comment]
instead of `default_middlewares.go` I think it should go into `middlewares/logger` as well.

**Comment by EwenQuim** [comment]
But it would mean in another module an not included by default, right?

**Comment by dylanhitt** [comment]
Hmmm, the more I think about this the more I’m realizing I’m thinking about ding too much.

yeah, let’s just to the default that you described. With a simple on/off. I am imagining middlewares/logger could exist eventually, but that would be a separate effort outside of fuego core. I think this default logger should aim for being just enough.

**Comment by EwenQuim** [comment]
Yeah just a basic logger will be enough. For advanced use cases, users won't be afraid to create their own.

**Comment by jwtly10** [comment]
Hey @dylanhitt @EwenQuim 

Am I OK to work on this issue?

One question about configurability - do we want to selectively enable/disable either the resp or req logs? Or just a global flag that turns off this middleware completely, so anyone is free to impl their own?

**Comment by EwenQuim** [comment]
I would say just a global on/off. But if you find a way to do both without too much downsides, you can do it.

I'm open to suggestions, do as you wish! :)

**Comment by dylanhitt** [comment]
@jwtly10 I played with the idea of doing it, but couldn't really find a pattern I liked for it. Basically what Ewen said if you can figure out way to do it cleanly please too. Here's some draft PRs of what my approach was.

- https://github.com/go-fuego/fuego/pull/294
- https://github.com/go-fuego/fuego/pull/293

If not I liked Ewen's idea of setting the request log to Debug.

**Comment by jwtly10** [comment]
Had a first stab at it, pretty much just building on what you did @dylanhitt (@EwenQuim)

[#303](https://github.com/go-fuego/fuego/pull/303)

Added some tests to show the API, I've tried to keep it simple and inline with existing options

**Comment by aidenwong812** [comment]
Can I try solving this issue?

**Comment by mimisavage** [comment]
I'd like to take this issue.

**Comment by EwenQuim** [comment]
@jwtly10 already did some great work on this issue and it's about to be merged. But #266 can be a nice first contribution!

**Comment by Emmy123222** [comment]
Let me try this one!

**Comment by Nityam573** [comment]
I’m interested in this one.

**Comment by VyuduInc** [comment]
Mind if I try this one?

**Comment by dylanhitt** [comment]
closed with #313

**Comment by dylanhitt** [comment]
closed with https://github.com/go-fuego/fuego/pull/313
