### ISSUE TITLE
Nix configuration

### ISSUE THREAD

**Issue by EwenQuim** [go-fuego/fuego#27]

**Comment by dylanhitt** [comment]
What does this mean out of curiosity?

**Comment by EwenQuim** [comment]
We meant using [nix](https://nixos.org/) in one of the examples.
It was proposed by @rizerkrof. I suggest to close this issue because no work has been done on it the past weeks, and I'm not willing to work on this. 

If someone wants to show its nix skills, then why not! Feel free to re-open this issue :)
