### ISSUE TITLE
Move `(Server).DisableOpenapi` to a route option

### ISSUE THREAD

**Issue by EwenQuim** [go-fuego/fuego#270]
The `(Server).DisableOpenapi` and the two functions below must be removed in favor of a route option named `fuego.OptionShowInOpenAPI(bool)` and its alias `option.ShowInOpenAPI(bool)`. Can be useful in some cases (the user is serving HTML for example...). 

```go
// Hide prevents the routes in this server or group from being included in the OpenAPI spec.
func (s *Server) Hide() *Server {
	s.DisableOpenapi = true
	return s
}

// Show allows displaying the routes. Activated by default so useless in most cases,
// but this can be useful if you deactivated the parent group.
func (s *Server) Show() *Server {
	s.DisableOpenapi = false
	return s
}
```

**Comment by dylanhitt** [comment]
@EwenQuim you cool with me grabbing this one. I actually haven't moved any server level stuff to the options pattern yet?

**Comment by EwenQuim** [comment]
No problem. As you saw I'm trying to create "good first issues" (easy, not priority) to try onboarding new contributors, but no problem for you to try to take one or two!

**Comment by dylanhitt** [comment]
I figured, and yes I also think it's best for me to avoid these, but I don't think i've touched a group level config since i showed up on this project figured it was a good time to refresh myself 😄
