### ISSUE TITLE
Could not return NoContent status code with empty body response

### ISSUE THREAD

**Issue by achichkov** [go-fuego/fuego#281]
**To Reproduce**

1. set up route with option.DefaultStatusCode(204)
2. define route as returning (any, error) and return nil, nil
3. use this route

**Expected behavior**
This route should return code 204

**Actual behavior**
200 is returned

**Screenshots**
![image](https://github.com/user-attachments/assets/5f52fc7a-31f6-4608-b92f-b9783617e477)

**Framework version (please check if it happens with the last
Fuego version before posting):**
0.16.2

**Go version (please check if it happens with the last Go version before posting):**
1.23

**Additional context**
Seems like this code (serve.go:138) is executed in the wrong order:
```
if reflect.TypeOf(ans) == nil {
    return
}

if route.DefaultStatusCode != 0 {
    w.WriteHeader(route.DefaultStatusCode)
}
```

**Comment by EwenQuim** [comment]
Exactly! A PR would be appreciated. 

I'll do it later today if necessary!
