### ISSUE TITLE
Implement faster json encoding in all places using gojson/jsoniter/sonic or provide a interface to implement custom parsers like in echo or fiber

### ISSUE THREAD

**Issue by spa5k** [go-fuego/fuego#45]
**Is your feature request related to a problem? Please describe.**
We can get better performance without much work if we can move from default encoding json to it's alternative, since they are many times faster - 
**Describe the solution you'd like**
Something like this - 

```go
app := fiber.New(fiber.Config{
        JSONEncoder: json.Marshal,
        JSONDecoder: json.Unmarshal,
    })
```
or 

```go
e := echo.New()
e.JSONSerializer = gojsonMapper.New()
```
**Describe alternatives you've considered**
We can obviously manually do it, but then again, it's more like free performance by default.

**Additional context**

**Comment by EwenQuim** [comment]
Hi @spa5k 

Thanks for the idea, it's a feature that would be very interesting to have in Fuego.

It's not something we plan to do at the moment, we have higher priority issues.

We of course accept all PRs :)

**Comment by EwenQuim** [comment]
You can do that by using the custom `Serialize` method, example here with [json-iterator](https://github.com/json-iterator/go)

```go
package main

import (
	"net/http"

	"github.com/go-fuego/fuego"
	jsoniter "github.com/json-iterator/go"
)

var json = jsoniter.ConfigCompatibleWithStandardLibrary

func main() {
	s := fuego.NewServer()

	s.Serialize = func(w http.ResponseWriter, ans any) {
		w.Header().Set("Content-Type", "text/plain")
		json.NewEncoder(w).Encode(ans)
	}

	fuego.Get(s, "/", helloWorld)

	s.Run()
}

func helloWorld(c fuego.ContextNoBody) (string, error) {
	return "Hello, World!", nil
}

```


I will add this information in the docs, thank you for this issue!
