### ISSUE TITLE
No method server.Use in last version

### ISSUE THREAD

**Issue by gonnafaraway** [go-fuego/fuego#49]
**To Reproduce**

1. Go to example https://go-fuego.github.io/fuego/docs/guides/middlewares
2. Paste code from app-lvl example
3. Error, unresolved reference Use...

**Expected behavior**
I expected middlewares to work properly.

**Screenshots**
![Снимок экрана от 2024-02-19 14-39-17](https://github.com/go-fuego/fuego/assets/35832930/599624cf-eb4d-4078-855d-a8da10a897f3)

**Framework version (please check if it happens with the last Fuego version before posting):0.10.4**

**Go version (please check if it happens with the last Go version before posting):1.21.0**

**Comment by guerinoni** [comment]
Is this a bug of docs or code? I can fix it

**Comment by EwenQuim** [comment]
I think this is a doc issue, this should be `fuego.Use(s, middleware)`. Sorry about that!

**Comment by gonnafaraway** [comment]
fix plz))

**Comment by EwenQuim** [comment]
This is fixed, to documentation page is now correct. You have to use this syntax


```go
fuego.Use(s, myMiddleware)
```
