### ISSUE TITLE
CORS doesn't work

### ISSUE THREAD

**Issue by guerinoni** [go-fuego/fuego#59]
**To Reproduce**

Take the basic example and just add 
```
	fuego.Use(s, cors.New(cors.Options{
		AllowedOrigins: []string{"*"},
		AllowedMethods: []string{"GET", "POST", "PUT", "DELETE", "OPTIONS"},
		AllowedHeaders: []string{"*"},
	}).Handler)
```

**Expected behavior**
I have a front end running on `localhost:3000` and hitting backend in `localhost:8080`, I got the error about missing CORS.

If I switch to another example i tried without fuego it is working
```
server := http.Server{
                Addr: "127.0.0.1:8080",
                Handler: cors.New(cors.Options{
                        AllowedOrigins: []string{"http://localhost:3000"},
                        AllowedMethods: []string{"GET", "POST", "PUT", "DELETE"},
                }).Handler(mux),
        }
```

**Screenshots**
<img width="803" alt="Screenshot 2024-03-01 at 12 59 54 PM" src="https://github.com/go-fuego/fuego/assets/41150432/4bad6ee7-b6d1-4688-b35d-213735ba58e2">

**Framework version (please check if it happens with the last Fuego version before posting):**
Latest 0.12

**Go version (please check if it happens with the last Go version before posting):**
Latest: go version go1.22.0 darwin/arm64

**Comment by EwenQuim** [comment]
Hi @guerinoni !

Are your routes declared before or after the middleware registration ?

**Comment by guerinoni** [comment]
> Hi @guerinoni !
> 
> Are your routes declared before or after the middleware registration ?

Does not matter, i see the same problem

**Comment by guerinoni** [comment]
```go
func (s *Server) Run() error {
	go s.generateOpenAPI()
	elapsed := time.Since(s.startTime)
	slog.Debug("Server started in "+elapsed.String(), "info", "time between since server creation (fuego.NewServer) and server startup (fuego.Run). Depending on your implementation, there might be things that do not depend on fuego slowing start time")
	slog.Info("Server running ✅ on http://localhost"+s.Server.Addr, "started in", elapsed.String())

	s.Server.Handler = cors.New(cors.Options{
		AllowedOrigins: []string{"*"},
		AllowedMethods: []string{"GET", "POST", "PUT", "DELETE"},
		AllowedHeaders: []string{"*"},
	}).Handler(s.Mux)

	return s.Server.ListenAndServe()
}
```

This fixes the problem

**Comment by EwenQuim** [comment]
I can help you solve your CORS issue if you want, but I don't think it is related to the framework, it works in my case!

---

**Result on a React app**:
Notice that the Access-Control-Allow-Origin is correctly set.
<img width="1644" alt="image" src="https://github.com/go-fuego/fuego/assets/46993939/b8a34c3c-80f9-4efc-b38e-634696707496">
<img width="421" alt="image" src="https://github.com/go-fuego/fuego/assets/46993939/0952aea0-a856-4452-8fad-8a9f90df88e8">


**Code**: 
<img width="980" alt="image" src="https://github.com/go-fuego/fuego/assets/46993939/d0b2a87b-cf5f-411d-a23c-013b4cf4e194">

**Comment by guerinoni** [comment]
I'm not able to make it work, can you attach your front end application? I can try with your code

**Comment by EwenQuim** [comment]
Can you show me the network error ? I want to see the preflight request

**Comment by guerinoni** [comment]
<img width="1013" alt="Screenshot 2024-03-06 at 2 18 28 PM" src="https://github.com/go-fuego/fuego/assets/41150432/56797093-6979-4d28-be2e-dbac0e59899a">
