### ISSUE TITLE
Custom group tags

### ISSUE THREAD

**Issue by EwenQuim** [go-fuego/fuego#62]
**Is your feature request related to a problem? Please describe.**
The possibility to add tags to a group, instead of all routes. For example, instead of adding the `Book` tag to all `/admin` routes, just add the tag to the `adminRoutes := fuego.Group(s, "/admin")`

**Describe the solution you'd like**

```go
adminRoutes := fuego.Group(s, "/admin").Tags("Admin")
```

**Comment by dylanhitt** [comment]
Hey @EwenQuim 

I'm thinking about picking this up as I have use case for it. A point of clarification

Should groups inherit from each other? I.e grandparent.Tags("foo") -> parent.Tags("bar") -> child.Tags("baz") would lead too:
  a. grandparent = foo
  b. parent = foo, bar
  c. child = foo, bar, baz

I could find any thing in the openapi docs that really provides guidance here.

**Comment by Shackelford-Arden** [comment]
As someone who'd use the inherited tags, I'd like it to at least be an option to allow tags to be inherited in the way that you mention, @dylanhitt. Seems to make sense to me, as at least in my case, it would ensure some organization in the UI for the API docs where things fall.

**Comment by EwenQuim** [comment]
I think we can add a `tags []string` to the `Server` struct.

The `fuego.Group()` would **copy** the field so no issues on the point (we should check that is does not impact other groups through extensive tests).

Maybe we can use an API that looks like the Route tags, for example `Tags` that replace the list and `AddTags` that adds a tag to the ones already present in the group.

**Comment by dylanhitt** [comment]
Beautiful, we're pretty much in the same thought pattern for an implementation. 

Expect a PR sometimes this weekend.

Cheers!
