### ISSUE TITLE
slog extensions

### ISSUE THREAD

**Issue by gedw99** [go-fuego/fuego#67]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when [...] I work on a great golang framework but I am trapped into their way of logging.

**Describe the solution you'd like**

slog is nicely extensible, and all of them are pretty much wrapped for standard go context here.
https://github.com/blink-io/x/tree/main/slog

https://github.com/samber?tab=repositories wrote the adapters . Huge thank you @samber

**Describe alternatives you've considered**

slog all the way :)

**Additional context**

I tend to log to NATS because its an async broker and so I can then stream / transform / save logs anywhere a NATS instance lives.

**Comment by EwenQuim** [comment]
Hey !

Thank you for your comment. I don't understand what you're looking for, a custom log handler ? You can use the `WithHandler` option in the `NewServer()` arguments.

**Comment by EwenQuim** [comment]
To be clear: Fuego already uses `log/slog`, and you can already use a custom handler.

I will update the documentation website, the [reference](https://pkg.go.dev/github.com/go-fuego/fuego#WithLogHandler) might not be enough.

Thank you for pointing that out!
