### ISSUE TITLE
Graceful shutdown of the http server

### ISSUE THREAD

**Issue by nengberg** [go-fuego/fuego#69]
Hey and thanks for an interesting library!

**Is your feature request related to a problem? Please describe.**

I have been looking around at the examples you've provided and the source code, but I cannot find a way to gracefully shut down the server. `fuego.Server` provides the function `Run() error`, which in turn calls `ListenAndServe` on the HTTP server. Let's say you want to gracefully shut down the server by listening to different signals, how would you do that?

**Describe the solution you'd like**
A Shutdown func on the server calling the Shutdown func on the `*http.Server`: https://cs.opensource.google/go/go/+/refs/tags/go1.22.1:src/net/http/server.go;l=2985

Something similar to this:

```
func (s *Server) Shutdown(ctx context.Context) error {
	return s.Server.Shutdown(ctx)
}
```

The you can incorporate that in your app in the following way:

```
func main() {
	s := fuego.NewServer(
		fuego.WithPort(":8088"),
	)

	fuego.Get(s, "/", func(c fuego.ContextNoBody) (string, error) {
		return "Hello, World!", nil
	})

	go func() {
		signals := make(chan os.Signal, 3)
		signal.Notify(signals, syscall.SIGINT, syscall.SIGTERM, syscall.SIGHUP)
		<-signals
		
		if err := s.Shutdown(ctx); err != nil{
			panic(err)
		}
	}()

	if err := s.Run(); err != nil && err != http.ErrServerClosed {
		panic(err)
	}
}
```

**Comment by EwenQuim** [comment]
> Something similar to this:
> 
> ```go
> func (s *Server) Shutdown(ctx context.Context) error {
> 	return s.Server.Shutdown(ctx)
> }
> ```

I don't think wrapping all methods from Server is a good idea, I made the `Server` field public for a reason!
If we want to make it more obvious, we might use the `Server` field as an embedded `*http.Server`, what do you think ?

**Comment by nengberg** [comment]
Yeah why not? Unless you want to log (like you do in `Run()`) I don't see any reason why you wouldn't just embed it!

**Comment by EwenQuim** [comment]
OK let's go embedding it for 0.13!
