### ISSUE TITLE
Default c.Body() err too `fuego.BadRequestError`

### ISSUE THREAD

**Issue by dylanhitt** [go-fuego/fuego#81]
**Is your feature request related to a problem? Please describe.**
The title says right now c.Body will just return the basic error from whatever marshaler it uses. What are the thoughts on defaulting to BadRequest as I can't think of a situation where this would be the servers fault for not being able to decode an object it can't understand.

**Describe the solution you'd like**

**Describe alternatives you've considered**
Right you get a lot of:

```go
d, err := c.Body()
if err != nil {
	c.SetStatus(400)
	return struct{}, err
}
```

**Comment by dylanhitt** [comment]
Meh, I guess the user could just 

```
d, err := c.Body()
if err != nil {
	return struct{}, fuego.BadRequestError{Err: err}
}
```
Which would end in the same amount of lines anyway.

**Comment by EwenQuim** [comment]
I agree that `c.Body()` must return a `BadRequestError`, we will change that
