### ISSUE TITLE
Only delete is excluded from route groups.

### ISSUE THREAD

**Issue by minpeter** [go-fuego/fuego#97]
ref: https://github.com/go-fuego/fuego/pull/96#issuecomment-2015642599

**To Reproduce**

1. Follow the tutorial crud.
2. In swagger, only the delete method does not belong to a group. (see bug)

**Expected behavior**
Naturally, it exists in the same group including `delete`

**Screenshots**
![image](https://github.com/go-fuego/fuego/assets/62207008/90f97fab-9792-4f38-87b4-9e7ef106a588)
```go
func (rs FilesRessources) Routes(s *fuego.Server) {
	filesGroup := fuego.Group(s, "/files")

	fuego.Get(filesGroup, "/", rs.getAllFiles)
	fuego.Post(filesGroup, "/", rs.postFiles)

	fuego.Get(filesGroup, "/{id}", rs.getFiles)
	fuego.Put(filesGroup, "/{id}", rs.putFiles)
	fuego.Delete(filesGroup, "/{id}", rs.deleteFiles)
}
```

**Framework version (please check if it happens with the last Fuego version before posting):**
latest

**Go version (please check if it happens with the last Go version before posting):**
`go version go1.22.1 linux/amd64`

**Comment by minpeter** [comment]
Paths using `Std lib compatibility` will also not belong to the group.

**Comment by EwenQuim** [comment]
You can Tag **manually** the routes with`.Tags()`, check the docs!

---

**Automatic** Tags are based on **return type**, not on the first `/<thing>`. This is why std lib routes and delete route (that does not have a return type!) arent registered with the tag you expect.

Does it seems more logical for you to tag them by the **first slash** ?

Should we have an option to choose between the 2 options (return type VS first slash) ?

Think about the `/books/<id>/authors` route. In which Tag must it belong ?

**Comment by minpeter** [comment]
Obviously books group tag,
From my point of view the first slash option looks quite good.

**Comment by EwenQuim** [comment]
I'll talk to the team about that. We might be doing this for the next release :)

**Comment by minpeter** [comment]
![image](https://github.com/go-fuego/fuego/assets/62207008/4dc132dd-16e9-40c9-81f9-155023e64101)

```go
func (rs FilesRessources) Routes(s *fuego.Server) {
	filesGroup := fuego.Group(s, "/files")
	fuego.Get(filesGroup, "/", rs.getAllFiles)
	fuego.Post(filesGroup, "/", rs.postFiles)
	fuego.GetStd(filesGroup, "/{id}/{name}", rs.downloadFile).Tags("files")
	fuego.Get(filesGroup, "/{id}", rs.getFiles)
	fuego.Delete(filesGroup, "/{id}", rs.deleteFiles)
}
```

.tags worked fine. thank you
